name: Auto PR Bot

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
      - "chore/**"
      - "hotfix/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or Update PR
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: ${{ github.ref_name }}
          title: "chore(bot): Auto PR → ${{ github.ref_name }} → main"
          body: |
            This PR was opened automatically by the bot.
            - Auto-merge: **enabled (squash)**
            - Vercel will attach a Preview in checks.
          labels: |
            preview
            automated
          draft: false

      - name: Enable auto-merge (squash)
        if: steps.cpr.outputs.pull-request-number != 
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

      - name: Comment with instructions
        if: steps.cpr.outputs.pull-request-url != 
        uses: actions/github-script@v7
        with:
          script: |
            const pr = ${{ steps.cpr.outputs.pull-request-number }};
            const body = `🤖 Auto-PR enabled.
            - Branch: \`${{ github.ref_name }}\`
            - Auto-merge: **enabled (squash)**
            - CI must pass for merge.
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body
            });
