name: Bot PR automático y auto-merge (ES)

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'
      - 'hotfix/**'

permissions:
  contents: write        # necesario para actualizar ramas/PRs
  pull-requests: write   # necesario para habilitar auto-merge

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Crea o actualiza un PR desde la rama actual hacia main
      - name: Crear/actualizar PR → main
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.ref_name }}"
          destination_branch: "main"
          pr_title: "Auto PR: ${{ github.ref_name }}"
          pr_body: |
            PR automático desde **${{ github.ref_name }}** hacia **main**.
            - Creado por workflow en español.
            - Se activará auto-merge (squash) cuando el CI pase 👍
          pr_label: "auto-pr"
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      # Habilita auto-merge (squash). 'gh' viene preinstalado en ubuntu-latest.
      - name: Activar auto-merge (squash)
        if: ${{ steps.pr.outputs.pr_number != '' }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "PR #${{ steps.pr.outputs.pr_number }}: habilitando auto-merge (squash)…"
          gh pr merge ${{ steps.pr.outputs.pr_number }} --auto --squash --delete-branch=false
