- name: Probar /api/health (build ya generado)
  shell: bash
  run: |
    node - <<'JS'
    (async () => {
      const mod = require('./.next/server/app/api/health/route.js');
      const handler =
        mod.GET ||
        mod.default ||
        mod.handler ||
        (mod.handlers && mod.handlers.GET);

      if (typeof handler !== 'function') {
        throw new Error('GET no es función en health/route.js');
      }

      const res = await handler();
      const data = await res.json();

      if (!Object.prototype.hasOwnProperty.call(data, 'env')) {
        throw new Error('Falta "env" en payload: ' + JSON.stringify(data));
      }
      if (data.ok !== true) {
        throw new Error('Health no OK: ' + JSON.stringify(data));
      }

      console.log('Health OK:', data);
    })().catch((e) => {
      console.error(e);
      process.exit(1);
    });
    JS
