name: CI

on:
  push:
    branches: [ main, feat/**, fix/**, chore/** ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint --max-warnings=0

      - name: Build
        env:
          # Público
          NEXT_PUBLIC_SUPABASE_URL: "https://stknnmgjasngbnpztgrh.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0a25ubWdqYXNuZ2JucHp0Z3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTc0MTYsImV4cCI6MjA3MTI5MzQxNn0.baK_7KOasYpXFADIlrsQPepb3DBItM1g2U-lDBjtSg0"
          NEXT_PUBLIC_SITE_URL: "https://oretec-web-9jgh.vercel.app"

          # Servidor (dummy en CI)
          SUPABASE_SERVICE_ROLE_KEY: "dummy-service"

          # Admin
          ADMIN_TOKEN: "dummy-token"
          ADMIN_BOOTSTRAP_EMAILS: "ci@dummy.local"

          # MercadoPago (dummy en CI)
          MP_PUBLIC_KEY: "dummy-mp-pub"
          MP_ACCESS_TOKEN: "dummy-mp-access"
          NEXT_PUBLIC_MP_ENV: "sandbox"

          CI: "true"
        run: npm run build

      - name: Test /api/health handler (built)
        run: |
          node -e "
            (async () => {
              const { GET } = require('./.next/server/app/api/health/route.js');
              const res = await GET();
              const data = await res.json();
              if (!data || data.ok !== true) {
                console.error('Health not OK:', data);
                process.exit(1);
              }
              if (!('env' in data)) {
                console.error('Missing env in health payload:', data);
                process.exit(1);
              }
              console.log('Health OK:', data);
            })().catch((e) => { console.error(e); process.exit(1); });
          "
