name: cleanup merged branches

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  delete_branch:
    if: >
      github.event.pull_request.merged == true &&
      !startsWith(github.head_ref, 'main') &&
      !startsWith(github.head_ref, 'release/') &&
      !startsWith(github.head_ref, 'dependabot/') &&
      !startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - name: Delete remote branch
        uses: actions/github-script@v7
        with:
          script: |
            const ref = `heads/${{ github.head_ref }}`;
            core.info(`Deleting remote ref: ${ref}`);
            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref
            });
            core.info('✅ Remote branch deleted');
