name: Delete merged branches automatically

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branches
        uses: beatlabs/delete-merged-branch@v6
        with:
          exclude: main,master
